version: "3.9"

services:

  apacheb1:
    build: ./apache
    container_name: apachen1
    ports:
      - "6001:80"
    depends_on:
      - pythonb1
    restart: unless-stopped

  pythonb1:
    build: .
    container_name: pythonb1
    env_file:
      - .env
    restart: unless-stopped

  mariadbb1:
    image: mariadb:11
    container_name: mariadbb1
    env_file:
      - .env
    volumes:
      - mariadb-datab1:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  phpmyadminb1:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminb1
    ports:
      - "7001:80"
    environment:
      PMA_HOST: mariadbb1
    depends_on:
      - mariadbb1
    restart: unless-stopped

volumes:
  mariadb-datab1:
