apiVersion: v1
kind: Secret
metadata:
  name: grupob1-secret
  namespace: grupob1
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: Z3ltX2FwcA==
  MYSQL_USER: YXBwdXNlcg==
  MYSQL_PASSWORD: QXBwUGFzc3dvcmQxMjMh
  DB_HOST: bWFyaWFkYmIx
  DB_PORT: MzMwNg==
  DB_DATABASE: Z3ltX2FwcA==
  DB_USERNAME: YXBwdXNlcg==
  DB_PASSWORD: QXBwUGFzc3dvcmQxMjMh
