apiVersion: v1
kind: Namespace
metadata:
  name: grupob1

---
apiVersion: v1
kind: Secret
metadata:
  name: grupob1-secret
  namespace: grupob1
type: Opaque
data:
  MYSQL_ROOT_PASSWORD=cm9vdA==
  MYSQL_DATABASE=Z3ltX2FwcA==
  MYSQL_USER=YXBwdXNlcg==
  MYSQL_PASSWORD=QXBwUGFzc3dvcmQxMjMh

  DB_HOST=bWFyaWFkYmIx
  DB_PORT=3306
  DB_NAME=Z3ltX2FwcA==
  DB_USER=YXBwdXNlcg==
